/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpacexCard {
        /**
          * Flight number
         */
        "flightnumber": string;
        /**
          * Image URL to display
         */
        "imageurl": string;
        /**
          * Land success
         */
        "landsuccess": string;
        /**
          * Launch success
         */
        "launchsuccess": string;
        /**
          * Launch year
         */
        "launchyear": string;
        /**
          * Mission Ids
         */
        "missionids": string;
        /**
          * Mission name
         */
        "missonname": string;
    }
    interface SpacexFooter {
    }
    interface SpacexHeader {
    }
    interface SpacexToggle {
        /**
          * The toggle checked property
         */
        "checked": boolean;
        /**
          * The toggle value
         */
        "value": any;
    }
}
declare global {
    interface HTMLSpacexCardElement extends Components.SpacexCard, HTMLStencilElement {
    }
    var HTMLSpacexCardElement: {
        prototype: HTMLSpacexCardElement;
        new (): HTMLSpacexCardElement;
    };
    interface HTMLSpacexFooterElement extends Components.SpacexFooter, HTMLStencilElement {
    }
    var HTMLSpacexFooterElement: {
        prototype: HTMLSpacexFooterElement;
        new (): HTMLSpacexFooterElement;
    };
    interface HTMLSpacexHeaderElement extends Components.SpacexHeader, HTMLStencilElement {
    }
    var HTMLSpacexHeaderElement: {
        prototype: HTMLSpacexHeaderElement;
        new (): HTMLSpacexHeaderElement;
    };
    interface HTMLSpacexToggleElement extends Components.SpacexToggle, HTMLStencilElement {
    }
    var HTMLSpacexToggleElement: {
        prototype: HTMLSpacexToggleElement;
        new (): HTMLSpacexToggleElement;
    };
    interface HTMLElementTagNameMap {
        "spacex-card": HTMLSpacexCardElement;
        "spacex-footer": HTMLSpacexFooterElement;
        "spacex-header": HTMLSpacexHeaderElement;
        "spacex-toggle": HTMLSpacexToggleElement;
    }
}
declare namespace LocalJSX {
    interface SpacexCard {
        /**
          * Flight number
         */
        "flightnumber"?: string;
        /**
          * Image URL to display
         */
        "imageurl"?: string;
        /**
          * Land success
         */
        "landsuccess"?: string;
        /**
          * Launch success
         */
        "launchsuccess"?: string;
        /**
          * Launch year
         */
        "launchyear"?: string;
        /**
          * Mission Ids
         */
        "missionids"?: string;
        /**
          * Mission name
         */
        "missonname"?: string;
    }
    interface SpacexFooter {
    }
    interface SpacexHeader {
    }
    interface SpacexToggle {
        /**
          * The toggle checked property
         */
        "checked"?: boolean;
        /**
          * The toggle value
         */
        "value"?: any;
    }
    interface IntrinsicElements {
        "spacex-card": SpacexCard;
        "spacex-footer": SpacexFooter;
        "spacex-header": SpacexHeader;
        "spacex-toggle": SpacexToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "spacex-card": LocalJSX.SpacexCard & JSXBase.HTMLAttributes<HTMLSpacexCardElement>;
            "spacex-footer": LocalJSX.SpacexFooter & JSXBase.HTMLAttributes<HTMLSpacexFooterElement>;
            "spacex-header": LocalJSX.SpacexHeader & JSXBase.HTMLAttributes<HTMLSpacexHeaderElement>;
            "spacex-toggle": LocalJSX.SpacexToggle & JSXBase.HTMLAttributes<HTMLSpacexToggleElement>;
        }
    }
}
